apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-hosts-deployment
  labels:
    app: legacy-hosts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: legacy-hosts
  template:
    metadata:
      labels:
        app: legacy-hosts
    spec:
      containers:
      - name: legacy-hosts
        image: registry.zeit.de/legacy-hosts:v0.1
        ports:
        - containerPort: 8080
