apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: legacy-hosts
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "images.zeit.de"
    http:
      paths:
      - backend:
          serviceName: legacy-hosts-service
          servicePort: 80
  - host: "zeus.zeit.de"
    http:
      paths:
      - backend:
          serviceName: legacy-hosts-service
          servicePort: 80
